import type { Metadata } from "next";
import { IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import AnimateWrapper from "./AnimateWrapper";
import AsideLeft from "@/components/AsideLeft";
import AsideRight from "@/components/AsideRight";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const ibmPlexMono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${ibmPlexMono.className} antialiased flex mx-auto h-screen overflow-hidden text-gray-900`}
      >
        <AsideLeft />
        <main className="flex-1 min-w-7/12 overflow-y-auto p-6 bg-gray-800 text-white">
         <div className="absolute inset-0 bg-[url('/home-transparent.png')] bg-repeat opacity-9 pointer-events-none -z-10"></div>
          <AnimateWrapper>{children}</AnimateWrapper>
        </main>
        <AsideRight />
        
      </body>
    </html>
  );
}
